module.exports = [
    "Clement of Rome": "Clement of Rome",
    "Mathetes": "Mathetes",
    "Polycarp": "Polycarp",
    "Ignatius": "Ignatius",
    "Barnabas": "Barnabas",
    "Papias": "Papias",
    "Justin Martyr": "Justin Martyr",
    "Irenaeus.": "Irenaeus",
    "Tertullian": "Tertullian",
    "The Pastor of Hermas": "The Pastor of Hermas",
    "Tatian": "Tatian",
    "Theophilus of Antioch": "Theophilus of Antioch",
    "Writings of Athenagoras": "Writings of Athenagoras",
    "Clement of Alexandria": "Clement of Alexandria",
    "Lactantius": "Lactantius",
    "Venantius": "Venantius",
    "Asterius Urbanus": "Asterius Urbanus",
    "Victorinus": "Victorinus",
    "Dionysius": "Dionysius",
    "Clement": "Clement",
    "Nicene Council": "Nicene Council",
    "Minucius Felix": "Minucius Felix",
    "Origen": "Origen",
    "The Epistles of Clement": "Clement",
    "Cyprian": "Cyprian",
    "Caius": "Caius",
    "Novatian": "Novatian",
    "Appendix": "Appendix",
    "St. Aurelius Augustin": "Augustine",
    "The Twelve Patriarchs": "The Twelve Patriarchs",
    "Theodotus": "Theodotus",
    "Pseudo-Clementine Literature": "Pseudo-Clementine Literature",
    "Apocrypha of the New Testament": "Apocrypha of the New Testament",
    "The Decretals": "The Decretals",
    "Memoirs of Edessa": "Memoirs of Edessa",
    "Augustine-Anti-Manichaean Writings": "Augustine",
    "Augustine-Anti-Donatist Writings": "Augustine",
    "Julius Africanus": "Julius Africanus",
    "Anatolius and Minor Writers.": "Anatolius and Minor Writers",
    "Alexander of Cappadocia.": "Alexander of Cappadocia",
    "Theognostus of Alexandria.": "Theognostus of Alexandria",
    "Pierius of Alexandria.1": "Pierius of Alexandria",
    "Theonas of Alexandria.": "Theonas of Alexandria",
    "Phileas.": "Phileas",
    "Pamphilus.": "Pamphilus",
    "Malchion.": "Malchion",
    "Archelaus.": "Archelaus",
    "Alexander": "Alexander",
    "Peter, Bishop of Alexandria": "Peter, Bishop of Alexandria",
    "Methodius": "Methodius",
    "Arnobius": "Arnobius",
    "St. John Chrysostom": "St. John Chrysostom",
    "Socrates Scholasticus.": "Socrates Scholasticus",
    "Hermias Sozomen": "Hermias Sozomen",
    "Eusebius Pamphilus": "Eusebius Pamphilus",
    "Theodoret": "Theodoret",
    "Jerome and Gennadius": "Jerome and Gennadius",
    "Rufinus": "Rufinus",
    "Gregory of Nyssa": "Gregory of Nyssa",
    "Athanasius, Bishop of Alexandria": "Athanasius",
    "Hilary of Poitiers": "Hilary of Poitiers",
    "John of Damascus.": "John of Damascus",
    "St. Ambrose": "St. Ambrose",
    "Sulpitius Severus": "Sulpitius Severus",
    "Vincent of Lerins": "Vincent of Lerins",
    "John Cassian": "John Cassian",
    "Ephraim the Syrian": "Ephraim the Syrian",
    "Ephraim Syrus": "Ephraim Syrus",
    "Aphrahat": "Aphrahat",
    "St. Basil": "St. Basil",
    "Gregory the Great": "Gregory the Great",
    "Cyril": "Cyril",
    "Gregory Nazianzen.": "Gregory Nazianzen",
    "The First Ecumenical Council; The First Council of Nice": "The First Ecumenical Council; The First Council of Nice",
    "The Canons of the Councils of Ancyra, Gangra Neocaesarea, Antioch and Laodicea": "The Canons of the Councils of Ancyra, Gangra Neocaesarea, Antioch and Laodicea",
    "The Second Ecumenical Council. The First Council of Constantinople.": "The Second Ecumenical Council. The First Council of Constantinople",
    "The Third Ecumenical Council.; The Council of Ephesus.": "The Third Ecumenical Council.; The Council of Ephesus",
    "The Fourth Ecumenical Council.; The Council of Chalcedon.": "The Fourth Ecumenical Council.; The Council of Chalcedon",
    "The Fifth Ecumenical Council. The Second Council of Constantinople.": "The Fifth Ecumenical Council. The Second Council of Constantinople",
    "The Sixth Ecumenical Council.; The Third Council of Constantinople.": "The Sixth Ecumenical Council.; The Third Council of Constantinople",
    "The Canons of the Council in Trullo; Often Called the Quinisext Council.": "The Canons of the Council in Trullo",
    "The Canons of the Synods of Sardica, Carthage, Constantinople, and Carthage": "The Canons of the Synods of Sardica, Carthage, Constantinople, and Carthage",
    "The Seventh Ecumenical Council. The Second Council of Nice.": "The Seventh Ecumenical Council. The Second Council of Nice."]
