const table = [
    {author: 'dionysisu',
     title: 'ecclesial_hierarchy',
     pattern: 'Eccl. Hier.',
     latinpattern: 'Eccles. Hier.'},
    {author: 'dionysisu',
     title: 'divine_names',
     pattern: 'Div. Nom.',
     latinpattern: 'divinis nominibus'},
    {author: 'augustine',
     title: 'city_of_god',
     pattern: 'De Civ. Dei',
     latinpattern: 'de Civ. Dei'},
    {author: 'augustine',
     title: 'literal_meaning_of_genesis',
     pattern: 'Gen. ad lit.',
     latinpattern: 'gen. ad lit.'},
    {author: 'augustine',
     title: 'arianism_and_other_heresies', // ??
     pattern: 'De Heres.',
     latinpattern: 'de heres'},
    {author: 'augustine',
     title: 'on_the_trinity', 
     pattern: 'De Trin.',
     latinpattern: 'de trin'},
    {author: 'augustine',
     title: 'homilies_on_john', 
     pattern: 'in Joan.',
     latinpattern: 'in Joan'},
    {author: 'augustine',
     title: 'misc_questions', 
     pattern: 'Questions.',
     latinpattern: 'questions.'},
    {author: 'augustine',
     title: 'on_christian_doctrine', 
     pattern: 'De Doctr. Christ.',
     latinpattern: 'de doctr. christ..'},
    {author: 'augustine',
     title: 'enchiridion', 
     pattern: 'Enchir.',
     latinpattern: 'enchir'},
    {author: 'augustine',
     title: 'confessions', 
     pattern: 'Confess.',
     latinpattern: 'confess'},
    {author: 'augustine',
     title: 'on_evil', 
     pattern: 'De Lib Arb.',
     latinpattern: 'de lib arb'},
    {author: 'augustine',
     title: 'on_music', 
     pattern: 'Music',
     latinpattern: 'music'},
    {author: 'hugh_of_st_victor',
     title: 'on_the_sacraments', 
     pattern: 'De Sacram',
     latinpattern: 'de sacram'},
    {author: 'boethius',
     title: 'consolation_of_philosophy', 
     pattern: 'De Consol.',
     latinpattern: 'de consol'},
    {author: 'boethius',
     title: 'on_the_trinity', 
     pattern: 'De Trin.',
     latinpattern: 'de trin'},
    {author: 'john_damascene',
     title: 'on_the_orthodox_faith', 
     pattern: 'De Fide Orth.',
     latinpattern: 'de fide orth'},
    {author: 'peter_lombard',
     title: 'sentences', 
     pattern: 'Sent.',
     latinpattern: 'Sent.'},
    {author: 'bonaventure',
     title: 'on_the_sentences', 
     pattern: 'Sent.',
     latinpattern: 'Sent.'},
    {author: 'albert_the_great',
     title: 'on_the_sentences', 
     pattern: 'Sent.',
     latinpattern: 'Sent.'},
    {author: 'alexander_of_hales',
     title: 'on_the_sentences', 
     pattern: 'Sent.',
     latinpattern: 'Sent.'},
    {author: 'ambrose',
     title: 'expositions_on_luke', 
     pattern: 'Expos. in Luc.',
     latinpattern: 'expos. in luc'},
    {author: 'ambrose',
     title: 'on_repentence', 
     pattern: 'De Poenit.',
     latinpattern: 'de poenit'},
    {author: 'ambrose',
     title: 'on_the_sacraments', 
     pattern: 'De Sacram.',
     latinpattern: 'de sacram'},
    {author: 'ambrose',
     title: 'on_the_mysteries', 
     pattern: 'De Mysteriis.',
     latinpattern: 'de mysteriis'},
    {author: 'jerome',
     title: 'letters', 
     pattern: 'Epistle.',
     latinpattern: 'epistle'},
    {author: 'origen',
     title: 'commentary_on_matthew', 
     pattern: 'in Matth.',
     latinpattern: 'in Matth'},
    {author: 'hilary_of_pontiers',
     title: 'commentary_on_matthew', 
     pattern: 'Comment. in Matth.',
     latinpattern: 'in Matth'},
    {author: 'ambrose',
     title: 'prosologium', 
     pattern: 'Prosolog.',
     latinpattern: 'prosolog'},
    {author: 'ambrose',
     title: 'monologium', 
     pattern: 'Monol.',
     latinpattern: 'monol'},
    {author: 'aristotle',
     title: 'nicomachean_ethics', 
     pattern: 'Ethic.',
     latinpattern: 'ethic'},
    {author: 'aristotle',
     title: 'metaphysics', 
     pattern: 'Metaph.',
     latinpattern: 'metaph'},
    {author: 'aristotle',
     title: 'Physics', 
     pattern: 'Phys.',
     latinpattern: 'ethic'},
    {author: 'aristotle',
     title: 'de_anima', 
     pattern: 'De Anima',
     latinpattern: 'ethic'},
    {author: 'aristotle',
     title: 'topics', 
     pattern: 'Topics',
     latinpattern: 'topics'},
    {author: 'aristotle',
     title: 'prior_analytics', 
     pattern: 'Prior. Anal.',
     latinpattern: 'prior. anal.'},
    {author: 'aristotle',
     title: 'posterior_analytics', 
     pattern: 'Poster',
     latinpattern: 'poster'},
    {author: 'aristotle',
     title: 'categories', 
     pattern: 'Categor',
     latinpattern: 'categor'},
    {author: 'aristotle',
     title: 'on_memory', 
     pattern: 'De Memoria',
     latinpattern: 'de memoria'},
    {author: 'aristotle',
     title: 'on_sense_and_sensibility', 
     pattern: 'De Sens. et Sensato',
     latinpattern: 'de sens et sensato'},
    {author: 'aristotle',
     title: 'on_generation_and_corruption', 
     pattern: 'De Gener',
     latinpattern: 'de gener'},
    {author: 'aristotle',
     title: 'on_generation_of_animals', 
     pattern: 'De Gener. Anim',
     latinpattern: 'de gener anim'},
    {author: 'aristotle',
     title: 'on_politics', 
     pattern: 'Polit',
     latinpattern: 'polit'},
];
